=== FaFre/bangs/data/bangs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Kagi Bangs Schema",
  "description": "This schema defines the structure for bangs used by Kagi Search",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "s": {
        "type": "string",
        "title": "Website Name",
        "description": "The name of the website associated with the bang."
      },
      "d": {
        "type": "string",
        "title": "Domain",
        "description": "The domain name of the website."
      },
      "ad": {
        "type": "string",
        "title": "Alternate Domain",
        "description": "The domain of the actual website if the bang searches another website, if applicable."
      },
      "t": {
        "type": "string",
        "title": "Trigger",
        "description": "The specific trigger word or phrase used to invoke the bang."
      },
      "u": {
        "type": "string",
        "title": "Template URL",
        "description": "The URL template to use when the bang is invoked, where `{{{s}}}` is replaced by the user's query."
      },
      "x": {
        "type": "string",
        "title": "Regex pattern",
        "description": "Regex pattern that can be used for parsing the query for more complex bangs, allowing substition using `$1`, `$2`, etc."
      },
      "c": {
        "type": "string",
        "title": "Category",
        "description": "The category of the website, if applicable.",
        "enum": [
          "Entertainment",
          "Man Page",
          "Multimedia",
          "News",
          "Online Services",
          "Region search",
          "Research",
          "Shopping",
          "Tech",
          "Translation"
        ]
      },
      "sc": {
        "type": "string",
        "title": "Subcategory",
        "description": "The subcategory of the website, if applicable."
      },
      "fmt": {
        "type": "array",
        "title": "Format",
        "description": "The format flags indicating how the query should be processed.",
        "uniqueItems": true,
        "minItems": 0,
        "maxItems": 3,
        "items": {
          "type": "string",
          "enum": [
            "open_base_path",
            "url_encode_placeholder",
            "url_encode_space_to_plus"
          ]
        }
      },
      "skip_tests": {
        "type": "boolean",
        "default": false,
        "description": "Whether specs should be run on this bang"
      }
    },
    "required": [
      "d",
      "s",
      "t",
      "u"
    ],
    "additionalProperties": false
  }
}

=== FaFre/bangs/data/kagi_bangs.json
[
  {
    "s": "Kagi Search TEST",
    "d": "kagi.com",
    "t": "k",
    "u": "/search?q={{{s}}}"
  },
  {
    "s": "Kagi Search",
    "d": "kagi.com",
    "t": "kagi",
    "u": "/search?q={{{s}}}"
  },
  {
    "s": "Kagi News",
    "d": "kagi.com",
    "t": "n",
    "u": "/news?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi News",
    "d": "kagi.com",
    "t": "news",
    "u": "/news?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Videos",
    "d": "kagi.com",
    "t": "v",
    "u": "/videos?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Videos",
    "d": "kagi.com",
    "t": "video",
    "u": "/videos?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Videos",
    "d": "kagi.com",
    "t": "videos",
    "u": "/videos?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Videos",
    "d": "kagi.com",
    "t": "vids",
    "u": "/videos?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Maps",
    "d": "kagi.com",
    "t": "m",
    "u": "/maps?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Maps",
    "d": "kagi.com",
    "t": "map",
    "u": "/maps?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Maps",
    "d": "kagi.com",
    "t": "maps",
    "u": "/maps?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "i",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "image",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "images",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "img",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "imgs",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "pics",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Images",
    "d": "kagi.com",
    "t": "pictures",
    "u": "/images?q={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Podcasts",
    "d": "kagi.com",
    "t": "p",
    "u": "/podcasts?q={{{s}}}"
  },
  {
    "s": "Kagi Podcasts",
    "d": "kagi.com",
    "t": "podcast",
    "u": "/podcasts?q={{{s}}}"
  },
  {
    "s": "Kagi Podcasts",
    "d": "kagi.com",
    "t": "podcasts",
    "u": "/podcasts?q={{{s}}}"
  },
  {
    "s": "Kagi Discussion",
    "d": "kagi.com",
    "t": "discussdoc",
    "u": "/discussdoc?url={{{s}}}"
  },
  {
    "s": "Kagi FastGPT",
    "d": "kagi.com",
    "t": "fgpt",
    "u": "/fastgpt?query={{{s}}}"
  },
  {
    "s": "Kagi Quick Answer",
    "d": "kagi.com",
    "t": "q",
    "u": "/search?q={{{s}}}&qa=true"
  },
  {
    "s": "Kagi Quick Answer",
    "d": "kagi.com",
    "t": "quick",
    "u": "/search?q={{{s}}}&qa=true"
  },
  {
    "s": "Kagi Universal Summarizer",
    "d": "kagi.com",
    "t": "sum",
    "u": "https://kagi.com/summarizer?url={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer",
    "d": "kagi.com",
    "t": "summarize",
    "u": "https://kagi.com/summarizer?url={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer",
    "d": "kagi.com",
    "t": "summarise",
    "u": "https://kagi.com/summarizer?url={{{s}}}",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Key Moments)",
    "d": "kagi.com",
    "t": "sumt",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=takeaway",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Key Moments)",
    "d": "kagi.com",
    "t": "sumk",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=takeaway",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Key Moments)",
    "d": "kagi.com",
    "t": "sumkey",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=takeaway",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Key Moments)",
    "d": "kagi.com",
    "t": "summarizekey",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=takeaway",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Key Moments)",
    "d": "kagi.com",
    "t": "summarisekey",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=takeaway",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Kagi Universal Summarizer (Summary)",
    "d": "kagi.com",
    "t": "summ",
    "u": "https://kagi.com/summarizer?url={{{s}}}&summary=summary",
    "fmt": [
      "url_encode_placeholder"
    ]
  },
  {
    "s": "Search in International",
    "d": "kagi.com",
    "t": "int",
    "u": "/search?q={{{s}}}&r=no_region",
    "c": "Region search"
  },
  {
    "s": "Search in Belarus",
    "d": "kagi.com",
    "t": "by",
    "u": "/search?q={{{s}}}&r=by",
    "c": "Region search"
  },
  {
    "s": "Search in Belize",
    "d": "kagi.com",
    "t": "bz",
    "u": "/search?q={{{s}}}&r=bz",
    "c": "Region search"
  },
  {
    "s": "Search in Benin",
    "d": "kagi.com",
    "t": "bj",
    "u": "/search?q={{{s}}}&r=bj",
    "c": "Region search"
  },
  {
    "s": "Search in Cayman Islands",
    "d": "kagi.com",
    "t": "ky",
    "u": "/search?q={{{s}}}&r=ky",
    "c": "Region search"
  },
  {
    "s": "Search in Central African Republic",
    "d": "kagi.com",
    "t": "cf",
    "u": "/search?q={{{s}}}&r=cf",
    "c": "Region search"
  },
  {
    "s": "Search in Christmas Island",
    "d": "kagi.com",
    "t": "cx",
    "u": "/search?q={{{s}}}&r=cx",
    "c": "Region search"
  },
  {
    "s": "Search in Colombia",
    "d": "kagi.com",
    "t": "co",
    "u": "/search?q={{{s}}}&r=co",
    "c": "Region search"
  },
  {
    "s": "Search in Czechia",
    "d": "kagi.com",
    "t": "cz",
    "u": "/search?q={{{s}}}&r=cz",
    "c": "Region search"
  },
  {
    "s": "Search in Croatia",
    "d": "kagi.com",
    "t": "hr",
    "u": "/search?q={{{s}}}&r=hr",
    "c": "Region search"
  },
  {
    "s": "Search in Cyprus",
    "d": "kagi.com",
    "t": "cy",
    "u": "/search?q={{{s}}}&r=cy",
    "c": "Region search"
  },
  {
    "s": "Search in Iran",
    "d": "kagi.com",
    "t": "ir",
    "u": "/search?q={{{s}}}&r=ir",
    "c": "Region search"
  },
  {
    "s": "Search in Indonesia",
    "d": "kagi.com",
    "t": "id",
    "u": "/search?q={{{s}}}&r=id",
    "c": "Region search"
  },
  {
    "s": "Search in Iraq",
    "d": "kagi.com",
    "t": "iq",
    "u": "/search?q={{{s}}}&r=iq",
    "c": "Region search"
  },
  {
    "s": "Search in Isle of Man",
    "d": "kagi.com",
    "t": "im",
    "u": "/search?q={{{s}}}&r=im",
    "c": "Region search"
  },
  {
    "s": "Search in Kazakhstan",
    "d": "kagi.com",
    "t": "kz",
    "u": "/search?q={{{s}}}&r=kz",
    "c": "Region search"
  },
  {
    "s": "Search in Kenya",
    "d": "kagi.com",
    "t": "ke",
    "u": "/search?q={{{s}}}&r=ke",
    "c": "Region search"
  },
  {
    "s": "Search in Kiribati",
    "d": "kagi.com",
    "t": "ki",
    "u": "/search?q={{{s}}}&r=ki",
    "c": "Region search"
  },
  {
    "s": "Search in Kuwait",
    "d": "kagi.com",
    "t": "kw",
    "u": "/search?q={{{s}}}&r=kw",
    "c": "Region search"
  },
  {
    "s": "Search in Liberia",
    "d": "kagi.com",
    "t": "lr",
    "u": "/search?q={{{s}}}&r=lr",
    "c": "Region search"
  },
  {
    "s": "Search in Libya",
    "d": "kagi.com",
    "t": "ly",
    "u": "/search?q={{{s}}}&r=ly",
    "c": "Region search"
  },
  {
    "s": "Search in Madagascar",
    "d": "kagi.com",
    "t": "mg",
    "u": "/search?q={{{s}}}&r=mg",
    "c": "Region search"
  },
  {
    "s": "Search in Malaysia",
    "d": "kagi.com",
    "t": "my",
    "u": "/search?q={{{s}}}&r=my",
    "c": "Region search"
  },
  {
    "s": "Search in New Zealand",
    "d": "kagi.com",
    "t": "nz",
    "u": "/search?q={{{s}}}&r=nz",
    "c": "Region search"
  },
  {
    "s": "Search in Norway",
    "d": "kagi.com",
    "t": "no",
    "u": "/search?q={{{s}}}&r=no",
    "c": "Region search"
  },
  {
    "s": "Search in Oman",
    "d": "kagi.com",
    "t": "om",
    "u": "/search?q={{{s}}}&r=om",
    "c": "Region search"
  },
  {
    "s": "Search in Qatar",
    "d": "kagi.com",
    "t": "qa",
    "u": "/search?q={{{s}}}&r=qa",
    "c": "Region search"
  },
  {
    "s": "Search in Réunion",
    "d": "kagi.com",
    "t": "re",
    "u": "/search?q={{{s}}}&r=re",
    "c": "Region search"
  },
  {
    "s": "Search in South Africa",
    "d": "kagi.com",
    "t": "za",
    "u": "/search?q={{{s}}}&r=za",
    "c": "Region search"
  },
  {
    "s": "Search in Taiwan",
    "d": "kagi.com",
    "t": "tw",
    "u": "/search?q={{{s}}}&r=tw",
    "c": "Region search"
  },
  {
    "s": "Search in Thailand",
    "d": "kagi.com",
    "t": "th",
    "u": "/search?q={{{s}}}&r=th",
    "c": "Region search"
  },
  {
    "s": "Search in Togo",
    "d": "kagi.com",
    "t": "tg",
    "u": "/search?q={{{s}}}&r=tg",
    "c": "Region search"
  },
  {
    "s": "Search in Tokelau",
    "d": "kagi.com",
    "t": "tk",
    "u": "/search?q={{{s}}}&r=tk",
    "c": "Region search"
  },
  {
    "s": "Search in Tonga",
    "d": "kagi.com",
    "t": "to",
    "u": "/search?q={{{s}}}&r=to",
    "c": "Region search"
  },
  {
    "s": "Search in U.S. Virgin Islands",
    "d": "kagi.com",
    "t": "vi",
